//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace WapXzone_VNM.DT_THCSService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServiceController", Namespace="http://tempuri.org/")]
    public partial class ServiceController : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryDataDCS_StandardOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDataDCS_CustomOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOrderDCS_StandardOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOrderDCS_CustomOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceController() {
            this.Url = global::WapXzone_VNM.Properties.Settings.Default.WapXzone_DT_THCSService_ServiceController;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryDataDCS_StandardCompletedEventHandler QueryDataDCS_StandardCompleted;
        
        /// <remarks/>
        public event QueryDataDCS_CustomCompletedEventHandler QueryDataDCS_CustomCompleted;
        
        /// <remarks/>
        public event QueryOrderDCS_StandardCompletedEventHandler QueryOrderDCS_StandardCompleted;
        
        /// <remarks/>
        public event QueryOrderDCS_CustomCompletedEventHandler QueryOrderDCS_CustomCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceController/QueryDataDCS_Standard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultData QueryDataDCS_Standard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string provinceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string commandCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string partnerId) {
            object[] results = this.Invoke("QueryDataDCS_Standard", new object[] {
                        smsId,
                        provinceCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId});
            return ((ResultData)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDataDCS_StandardAsync(string smsId, string provinceCode, string number, string requestId, string commandCode, string serviceId, string partnerId) {
            this.QueryDataDCS_StandardAsync(smsId, provinceCode, number, requestId, commandCode, serviceId, partnerId, null);
        }
        
        /// <remarks/>
        public void QueryDataDCS_StandardAsync(string smsId, string provinceCode, string number, string requestId, string commandCode, string serviceId, string partnerId, object userState) {
            if ((this.QueryDataDCS_StandardOperationCompleted == null)) {
                this.QueryDataDCS_StandardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDataDCS_StandardOperationCompleted);
            }
            this.InvokeAsync("QueryDataDCS_Standard", new object[] {
                        smsId,
                        provinceCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId}, this.QueryDataDCS_StandardOperationCompleted, userState);
        }
        
        private void OnQueryDataDCS_StandardOperationCompleted(object arg) {
            if ((this.QueryDataDCS_StandardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDataDCS_StandardCompleted(this, new QueryDataDCS_StandardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceController/QueryDataDCS_Custom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultData QueryDataDCS_Custom([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string provinceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string schoolCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string commandCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string partnerId) {
            object[] results = this.Invoke("QueryDataDCS_Custom", new object[] {
                        smsId,
                        provinceCode,
                        schoolCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId});
            return ((ResultData)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDataDCS_CustomAsync(string smsId, string provinceCode, string schoolCode, string number, string requestId, string commandCode, string serviceId, string partnerId) {
            this.QueryDataDCS_CustomAsync(smsId, provinceCode, schoolCode, number, requestId, commandCode, serviceId, partnerId, null);
        }
        
        /// <remarks/>
        public void QueryDataDCS_CustomAsync(string smsId, string provinceCode, string schoolCode, string number, string requestId, string commandCode, string serviceId, string partnerId, object userState) {
            if ((this.QueryDataDCS_CustomOperationCompleted == null)) {
                this.QueryDataDCS_CustomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDataDCS_CustomOperationCompleted);
            }
            this.InvokeAsync("QueryDataDCS_Custom", new object[] {
                        smsId,
                        provinceCode,
                        schoolCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId}, this.QueryDataDCS_CustomOperationCompleted, userState);
        }
        
        private void OnQueryDataDCS_CustomOperationCompleted(object arg) {
            if ((this.QueryDataDCS_CustomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDataDCS_CustomCompleted(this, new QueryDataDCS_CustomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceController/QueryOrderDCS_Standard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultData QueryOrderDCS_Standard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string provinceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string commandCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string partnerId) {
            object[] results = this.Invoke("QueryOrderDCS_Standard", new object[] {
                        smsId,
                        provinceCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId});
            return ((ResultData)(results[0]));
        }
        
        /// <remarks/>
        public void QueryOrderDCS_StandardAsync(string smsId, string provinceCode, string number, string requestId, string commandCode, string serviceId, string partnerId) {
            this.QueryOrderDCS_StandardAsync(smsId, provinceCode, number, requestId, commandCode, serviceId, partnerId, null);
        }
        
        /// <remarks/>
        public void QueryOrderDCS_StandardAsync(string smsId, string provinceCode, string number, string requestId, string commandCode, string serviceId, string partnerId, object userState) {
            if ((this.QueryOrderDCS_StandardOperationCompleted == null)) {
                this.QueryOrderDCS_StandardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOrderDCS_StandardOperationCompleted);
            }
            this.InvokeAsync("QueryOrderDCS_Standard", new object[] {
                        smsId,
                        provinceCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId}, this.QueryOrderDCS_StandardOperationCompleted, userState);
        }
        
        private void OnQueryOrderDCS_StandardOperationCompleted(object arg) {
            if ((this.QueryOrderDCS_StandardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryOrderDCS_StandardCompleted(this, new QueryOrderDCS_StandardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceController/QueryOrderDCS_Custom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultData QueryOrderDCS_Custom([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string smsId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string provinceCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string schoolCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string requestId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string commandCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string serviceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string partnerId) {
            object[] results = this.Invoke("QueryOrderDCS_Custom", new object[] {
                        smsId,
                        provinceCode,
                        schoolCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId});
            return ((ResultData)(results[0]));
        }
        
        /// <remarks/>
        public void QueryOrderDCS_CustomAsync(string smsId, string provinceCode, string schoolCode, string number, string requestId, string commandCode, string serviceId, string partnerId) {
            this.QueryOrderDCS_CustomAsync(smsId, provinceCode, schoolCode, number, requestId, commandCode, serviceId, partnerId, null);
        }
        
        /// <remarks/>
        public void QueryOrderDCS_CustomAsync(string smsId, string provinceCode, string schoolCode, string number, string requestId, string commandCode, string serviceId, string partnerId, object userState) {
            if ((this.QueryOrderDCS_CustomOperationCompleted == null)) {
                this.QueryOrderDCS_CustomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOrderDCS_CustomOperationCompleted);
            }
            this.InvokeAsync("QueryOrderDCS_Custom", new object[] {
                        smsId,
                        provinceCode,
                        schoolCode,
                        number,
                        requestId,
                        commandCode,
                        serviceId,
                        partnerId}, this.QueryOrderDCS_CustomOperationCompleted, userState);
        }
        
        private void OnQueryOrderDCS_CustomOperationCompleted(object arg) {
            if ((this.QueryOrderDCS_CustomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryOrderDCS_CustomCompleted(this, new QueryOrderDCS_CustomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/DataEntities")]
    public partial class ResultData {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryDataDCS_StandardCompletedEventHandler(object sender, QueryDataDCS_StandardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDataDCS_StandardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDataDCS_StandardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryDataDCS_CustomCompletedEventHandler(object sender, QueryDataDCS_CustomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDataDCS_CustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDataDCS_CustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryOrderDCS_StandardCompletedEventHandler(object sender, QueryOrderDCS_StandardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryOrderDCS_StandardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryOrderDCS_StandardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QueryOrderDCS_CustomCompletedEventHandler(object sender, QueryOrderDCS_CustomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryOrderDCS_CustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryOrderDCS_CustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591