//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WapXzone_VNM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://203.162.70.72:8094/MOReceiver.asmx")]
        public string WapXzone_GameUrl_MOReceiver {
            get {
                return ((string)(this["WapXzone_GameUrl_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://203.162.70.72:8067/MOReceiver.asmx")]
        public string WapXzone_CreateAvatar_MOReceiver {
            get {
                return ((string)(this["WapXzone_CreateAvatar_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://203.162.70.72:8094/MOReceiver.asmx")]
        public string WapXzone_GameUrl_MOReceiver1 {
            get {
                return ((string)(this["WapXzone_GameUrl_MOReceiver1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8193/Ws_Process.asmx")]
        public string WapXzone_CreateGIFAvatar_Ws_Process {
            get {
                return ((string)(this["WapXzone_CreateGIFAvatar_Ws_Process"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8094/MOReceiver.asmx")]
        public string WapXzone_VMGGame_MOReceiver {
            get {
                return ((string)(this["WapXzone_VMGGame_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.30.181.21/THPTService.svc")]
        public string WapXzone_DT_THPTService_ServiceController {
            get {
                return ((string)(this["WapXzone_DT_THPTService_ServiceController"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.30.181.21:8080/THCSService.svc")]
        public string WapXzone_DT_THCSService_ServiceController {
            get {
                return ((string)(this["WapXzone_DT_THCSService_ServiceController"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8067/MOReceiver.asmx")]
        public string MobiFoneWap_CreateAvatar_MOReceiver {
            get {
                return ((string)(this["MobiFoneWap_CreateAvatar_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8094/MOReceiver.asmx")]
        public string VietnamobileWap_GameUrl_MOReceiver {
            get {
                return ((string)(this["VietnamobileWap_GameUrl_MOReceiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.30.181.21:8081/TSDHService.svc")]
        public string WapXzone_VNM_WS_TSDHService_ServiceController {
            get {
                return ((string)(this["WapXzone_VNM_WS_TSDHService_ServiceController"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.30.181.21:8081/TSDHService.svc")]
        public string WapXzone_VNM_DT_TSDHService_ServiceController {
            get {
                return ((string)(this["WapXzone_VNM_DT_TSDHService_ServiceController"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://203.128.246.86/WSInterface/services/webservice_elcom")]
        public string WapXzone_VNMCharging_Billing {
            get {
                return ((string)(this["WapXzone_VNMCharging_Billing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:8001/PortalCharging/services/Charging")]
        public string WapXzone_VNM_WS_VNMCGW_webservice_elcom {
            get {
                return ((string)(this["WapXzone_VNM_WS_VNMCGW_webservice_elcom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dl.waptretho.vn:8080/cskh_ws/Service.asmx")]
        public string WapXzone_VNM_AppPaymentInfo_Service {
            get {
                return ((string)(this["WapXzone_VNM_AppPaymentInfo_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.29.67.200:8401/MsisdnService.asmx")]
        public string WapXzone_VNM_MsisdnService_MsisdnService {
            get {
                return ((string)(this["WapXzone_VNM_MsisdnService_MsisdnService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9203/WebServiceCharging3g.asmx")]
        public string WapXzone_VNM_WS_VNMCGW2G_CHARGING {
            get {
                return ((string)(this["WapXzone_VNM_WS_VNMCGW2G_CHARGING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9005/MOProcessor.asmx")]
        public string WapXzone_VNM_NhacChoSub_MOProcessor {
            get {
                return ((string)(this["WapXzone_VNM_NhacChoSub_MOProcessor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:9004/GetAvatarThumb.asmx")]
        public string WapXzone_VNM_vn_xzone_media_TinTucTheThaoSo_GetAvatarThumb {
            get {
                return ((string)(this["WapXzone_VNM_vn_xzone_media_TinTucTheThaoSo_GetAvatarThumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.29.67.71:8007/S2Vnm1119Service.asmx")]
        public string WapXzone_VNM_WsDvTet_S2Vnm1119Service {
            get {
                return ((string)(this["WapXzone_VNM_WsDvTet_S2Vnm1119Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vmgame.vn/Service_RegisS2.asmx")]
        public string WapXzone_VNM_VMgame_Service_RegisS2 {
            get {
                return ((string)(this["WapXzone_VNM_VMgame_Service_RegisS2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://123.29.67.174:8001/S2Process.asmx")]
        public string WapXzone_VNM_POD_S2Process {
            get {
                return ((string)(this["WapXzone_VNM_POD_S2Process"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9005/ServiceHandlers/NC1_Handler.asmx")]
        public string WapXzone_VNM_RingTone_NC1_Handler {
            get {
                return ((string)(this["WapXzone_VNM_RingTone_NC1_Handler"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://media.xzone.vn:8094/GameHandler.asmx")]
        public string WapXzone_VNM_Ws_Game94x_GameHandler {
            get {
                return ((string)(this["WapXzone_VNM_Ws_Game94x_GameHandler"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:8340/WS_VNMChelsea.asmx")]
        public string WapXzone_VNM_WS_VNMChelsea_WS_VNMChelsea {
            get {
                return ((string)(this["WapXzone_VNM_WS_VNMChelsea_WS_VNMChelsea"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv36.vmgmedia.vn:9005/S2Vnm.asmx")]
        public string WapXzone_VNM_S2VNM_S2Vnm {
            get {
                return ((string)(this["WapXzone_VNM_S2VNM_S2Vnm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv56.vmgmedia.vn:8000/ProcessMO.asmx")]
        public string WapXzone_VNM_RegisGamePT_ProcessMO {
            get {
                return ((string)(this["WapXzone_VNM_RegisGamePT_ProcessMO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sv167.vmgmedia.vn:8000/WebService.asmx")]
        public string WapXzone_VNM_WSVisport_WebService {
            get {
                return ((string)(this["WapXzone_VNM_WSVisport_WebService"]));
            }
        }
    }
}
